// Code generated by MockGen. DO NOT EDIT.
// Source: model.go

// Package mock_model is a generated GoMock package.
package mock_model

import (
	model "20dojo-online/pkg/server/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockModelInterface is a mock of ModelInterface interface.
type MockModelInterface struct {
	ctrl     *gomock.Controller
	recorder *MockModelInterfaceMockRecorder
}

// MockModelInterfaceMockRecorder is the mock recorder for MockModelInterface.
type MockModelInterfaceMockRecorder struct {
	mock *MockModelInterface
}

// NewMockModelInterface creates a new mock instance.
func NewMockModelInterface(ctrl *gomock.Controller) *MockModelInterface {
	mock := &MockModelInterface{ctrl: ctrl}
	mock.recorder = &MockModelInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModelInterface) EXPECT() *MockModelInterfaceMockRecorder {
	return m.recorder
}

// SelectCollectionItemAll mocks base method.
func (m *MockModelInterface) SelectCollectionItemAll() ([]*model.CollectionItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectCollectionItemAll")
	ret0, _ := ret[0].([]*model.CollectionItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectCollectionItemAll indicates an expected call of SelectCollectionItemAll.
func (mr *MockModelInterfaceMockRecorder) SelectCollectionItemAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectCollectionItemAll", reflect.TypeOf((*MockModelInterface)(nil).SelectCollectionItemAll))
}

// SelectUserCollectionsByUserID mocks base method.
func (m *MockModelInterface) SelectUserCollectionsByUserID(arg0 string) ([]*model.UserCollectionItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectUserCollectionsByUserID", arg0)
	ret0, _ := ret[0].([]*model.UserCollectionItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectUserCollectionsByUserID indicates an expected call of SelectUserCollectionsByUserID.
func (mr *MockModelInterfaceMockRecorder) SelectUserCollectionsByUserID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectUserCollectionsByUserID", reflect.TypeOf((*MockModelInterface)(nil).SelectUserCollectionsByUserID), arg0)
}
